name: mail-ai-agent
include:
  - ./deploy/docker-compose.common.yml
services:
  mailpit:
    image: axllent/mailpit:latest
    environment:
      - "MP_SMTP_AUTH_ACCEPT_ANY=true"
      - "MP_SMTP_AUTH_ALLOW_INSECURE=true"
      - "MP_POP3_BINDADDR=0.0.0.0:1110"
      - "MP_POP3_AUTH=pop3_user@example.com:pop3_password"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./.data/app:/data
    depends_on:
      ollama:
        condition: service_healthy